const TEAMS = {
  AR: {
    ALDOSIVI: 'Aldosivi',
    ARGENTINOS_JUNIORS: 'Argentinos Juniors',
    ARSENAL: 'Arsenal',
    ATLETICO_TUCUMAN: 'Atletico Tucumán',
    BANFIELD: 'Banfield',
    BARRACAS_CENTRAL: 'Barracas Central',
    BOCA_JUNIORS: 'Boca Juniors',
    CENTRAL_CORDOBA: 'Central Cordoba',
    COLON: 'Colón',
    DEFENSA_JUSTICIA: 'Defensa y Justicia',
    ESTUDIANTES_LP: 'Estudiantes L.P.',
    GIMNASIA_LP: 'Gimnasia L.P.',
    GODOY_CRUZ: 'Godoy Cruz',
    HURACAN: 'Huracán',
    INDEPENDIENTE: 'Independiente',
    LANUS: 'Lanús',
    NEWELLS: 'Newell\'s Old Boys',
    PATRONATO: 'Patronato',
    PLATENSE: 'Platense',
    RACING: 'Racing Club',
    RIVER: 'River Plate',
    ROSARIO_CENTRAL: 'Rosario Central',
    SAN_LORENZO: 'San Lorenzo',
    SARMIENTO: 'Sarmiento',
    TALLERES: 'Talleres',
    TIGRE: 'Tigre',
    UNION: 'Unión',
    VELEZ: 'Vélez',
  },
  EN: {
    ARSENAL: 'Arsenal',
    ASTON_VILLA: 'Aston Villa',
    BOURNEMOUTH: 'Bournemouth',
    BRENTFORD: 'Brentford',
    BRIGHTON: 'Brighton',
    CHELSEA: 'Chelsea',
    CRYSTAL_PALACE: 'Crystal Palace',
    EVERTON: 'Everton',
    FULHAM: 'Fulham',
    LEEDS: 'Leeds',
    LEICESTER: 'Leicester',
    LIVERPOOL: 'Liverpool',
    MANCHESTER_CITY: 'Manchester City',
    MANCHESTER_UTD: 'Manchester Utd',
    NEWCASTLE: 'Newcastle',
    NOTTINGHAM: 'Nottingham',
    SOUTHAMPTON: 'Southampton',
    TOTTENHAM: 'Tottenham',
    WEST_HAM: 'West Ham',
    WOLVES: 'Wolves',
  },
  ES: {
    ALMERIA: 'Almería',
    ATHLETIC_CLUB: 'Athletic Club',
    ATLETICO_MADRID: 'Atlético de Madrid',
    BARCELONA: 'Barcelona',
    CADIZ: 'Cádiz CF',
    CELTA_VIGO: 'Celta de Vigo',
    ELCHE: 'Elche',
    ESPANYOL: 'Espanyol',
    GETAFE: 'Getafe',
    GIRONA: 'Girona',
    MALLORCA: 'Mallorca',
    OSASUNA: 'Osasuna',
    RAYO_VALLECANO: 'Rayo Vallecano',
    REAL_BETIS: 'Betis',
    REAL_MADRID: 'Real Madrid',
    REAL_SOCIEDAD: 'Real Sociedad',
    SEVILLA: 'Sevilla',
    VALENCIA: 'Valencia',
    VALLADOLID: 'Valladolid',
    VILLARREAL: 'Villareal',
  },
  F1: {
    FERRARI: 'Ferrari',
    RED_BULL: 'Red Bull Racing',
    MERCEDES: 'Mercedes',
    ALPINE: 'Alpine',
    MCLAREN: 'McLaren',
    ALFA_ROMEO: 'Alfa Romeo',
    HAAS: 'Haas F1 Team',
    ALPHATAURI: 'AlphaTauri',
    ASTON_MARTIN: 'Aston Martin',
    WILLIAMS: 'Williams'
  }
};

module.exports = {
  TEAMS,
}
